"""Curate the codeword vocabulary into codewords/.

Words are concrete and picturable, <=8 chars, A-Z only, phonetically
distinct (no shared Soundex, edit distance >= 2), and free of NATO
alphabet collisions.
"""
import os
import re
from pathlib import Path

OUT = Path("/home/user/otp/codewords")

NATO = {
    "ALFA", "ALPHA", "BRAVO", "CHARLIE", "DELTA", "ECHO", "FOXTROT", "GOLF",
    "HOTEL", "INDIA", "JULIETT", "JULIET", "KILO", "LIMA", "MIKE", "NOVEMBER",
    "OSCAR", "PAPA", "QUEBEC", "ROMEO", "SIERRA", "TANGO", "UNIFORM", "VICTOR",
    "WHISKEY", "XRAY", "YANKEE", "ZULU",
}

# Casualties of the 8-character cap. A codeword has to be sayable and
# picturable; "MONASTER" is neither, so these are dropped rather than shipped
# in mangled form.
TRUNCATED = {
    "ALABAST", "LIMESTON", "MAGNETIT", "MALACHIT", "SANDSTON", "TOURMALI",
    "TRAVERTI", "TURQUOIS", "PALLADIU", "HOARFROS", "LIGHTNIN", "WHIRLWIN",
    "WATERFAL", "JACKPLAN", "XYLOPHON", "SUPERNOV", "BRIGAN", "CATAMARA",
    "DRAWBRID", "LIGHTHOU", "MILLHOUS", "MONASTER", "WATCHTOW", "COBALTIC",
    "GARNETIC", "HELIOTRO", "PERIWINK", "VERMILIO", "BARRACUD", "DAMSELFL",
    "CENTIPED", "MILLIPED", "TARANTUL", "WOODLOUS", "CRANBERR", "GABARDIN",
    "SEERSUCK", "EUCALYPT", "KINGFISH", "SANDPIPE", "LINGERIN", "PATTERED",
    "SHUTTERE", "TARNISHE", "THUNDERI", "WANDERIN", "WEATHERE", "WHISPERI",
    "WINDSWEP", "BUMBLE", "SILKS", "PLANTAIN", "BRAMBLES", "CHERRIES",
    "OLIVINE", "ANVILS", "MONSOONS", "SACKBUT", "REBEC", "COBLE", "URIAL",
}

# Words that would read as instructions or procedure over a voice channel.
PROCEDURAL = {
    "ABORT", "AFFIRM", "BREAK", "CANCEL", "CLEAR", "CORRECT", "OUT", "OVER",
    "READY", "RELAY", "REPEAT", "ROGER", "SAY", "SEND", "STOP", "WAIT", "WILCO",
    "MESSAGE", "GROUP", "PAGE", "KEY", "PAD", "CODE", "AUTH", "DUMMY", "NUMBER",
}

RAW = {
"animals": """
BADGER BEAVER BISON BOBCAT CAMEL CARIBOU COUGAR COYOTE DINGO DOLPHIN DONKEY
ELAND ELK FERRET FOX GAZELLE GECKO GERBIL GIBBON GOAT GOPHER GRIZZLY HARE
HEDGEHOG HIPPO HYENA IBEX IGUANA JACKAL JAGUAR KOALA LEMUR LEOPARD LLAMA LYNX
MAMMOTH MARMOT MARTEN MOLE MONGOOSE MOOSE MULE MUSKOX NARWHAL OCELOT OTTER
PANDA PANGOLIN PANTHER PECCARY PORPOISE POSSUM PUMA RACCOON RAM REINDEER
RHINO SABLE SEAL SERVAL SHREW SKUNK SLOTH STOAT TAPIR TIGER VICUNA VOLE
WALRUS WARTHOG WEASEL WOMBAT YAK ZEBRA ANTELOPE BUFFALO CHEETAH CIVET
COLOBUS FENNEC GAUR IMPALA KUDU MEERKAT NUMBAT ORYX QUOKKA SAIGA TAMARIN
URIAL WAPITI ADDAX BINTURONG CAPYBARA DUGONG ECHIDNA GENET HARTEBEEST
INDRI JERBOA KIANG MARKHOR NILGAI OKAPI POTTO SIFAKA TAKIN
""",
"birds": """
ALBATROSS AVOCET BITTERN BUNTING BUZZARD CONDOR CORMORANT CRANE CROW CUCKOO
CURLEW DUNLIN EAGLE EGRET FALCON FINCH FULMAR GANNET GODWIT GOSHAWK GREBE
GULL HARRIER HERON HOOPOE IBIS JACKDAW JAY KESTREL KINGFISH KITE KITTIWAKE
LAPWING LINNET MAGPIE MALLARD MARTIN MERLIN NIGHTJAR NUTHATCH ORIOLE OSPREY
OUZEL OWL PARAKEET PEACOCK PELICAN PETREL PHEASANT PIPIT PLOVER PUFFIN
QUAIL RAVEN REDSHANK ROBIN ROOK SANDPIPE SHRIKE SISKIN SKUA SKYLARK SNIPE
SPARROW STARLING STORK SWALLOW SWAN SWIFT TEAL TERN THRUSH TOUCAN TURNSTONE
VULTURE WAGTAIL WARBLER WAXWING WHEATEAR WIGEON WOODCOCK WREN
""",
"trees": """
ALDER ASPEN BALSA BAOBAB BASSWOOD BEECH BIRCH BOXWOOD BUCKEYE CEDAR CHERRY
CHESTNUT CYPRESS DOGWOOD EBONY ELDER ELM EUCALYPT FIR GINKGO HAWTHORN
HAZEL HEMLOCK HICKORY HOLLY HORNBEAM IRONWOOD JUNIPER LARCH LAUREL LINDEN
LOCUST MAGNOLIA MAHOGANY MANGROVE MAPLE MULBERRY OAK OLIVE PALM PECAN
PERSIMMON PINE PLANE POPLAR REDWOOD ROSEWOOD ROWAN SANDAL SEQUOIA SPRUCE
SYCAMORE TAMARISK TEAK THORN WALNUT WILLOW YEW BRACKEN BRAMBLE CLOVER
FERN GORSE HEATHER IVY LICHEN MOSS NETTLE REED RUSH SEDGE THISTLE
""",
"minerals": """
AGATE ALABAST AMBER AMETHYST BASALT BERYL CALCITE CHALK CINNABAR CITRINE
COAL CORAL CRYSTAL DIAMOND DOLOMITE EMERALD FELDSPAR FLINT GALENA GARNET
GNEISS GRANITE GRAPHITE GYPSUM HEMATITE JADE JASPER LIMESTON MAGNETIT
MALACHIT MARBLE MICA OBSIDIAN ONYX OPAL PEARL PERIDOT PUMICE PYRITE QUARTZ
RUBY SANDSTON SAPPHIRE SCHIST SHALE SILICA SLATE SPINEL TALC TOPAZ
TOURMALI TRAVERTI TURQUOIS ZIRCON
""",
"metals": """
ALUMINUM ANTIMONY BISMUTH BRASS BRONZE CADMIUM CHROME COBALT COPPER GALLIUM
GOLD INDIUM IRIDIUM IRON LEAD LITHIUM MERCURY NICKEL NIOBIUM OSMIUM
PALLADIU PEWTER PLATINUM RHODIUM SILVER SOLDER STEEL TANTALUM THORIUM TIN
TITANIUM TUNGSTEN URANIUM VANADIUM ZINC ALLOY ANVIL FILINGS INGOT LODE
SMELTER
""",
"weather": """
BLIZZARD BREEZE CIRRUS CLOUD CYCLONE DELUGE DOWNPOUR DRIZZLE DROUGHT
FLURRY FOG FROST GALE HAIL HAZE HOARFROS ICICLE LIGHTNIN MIST MONSOON
NIMBUS OVERCAST RAIN RAINBOW SHOWER SLEET SMOG SNOW SQUALL STORM STRATUS
SUNSHINE TEMPEST THAW THUNDER TORNADO TYPHOON VAPOR WHIRLWIN WIND ZEPHYR
DEWFALL DRIFT MONSOONS
""",
"landforms": """
ATOLL BADLANDS BASIN BAY BLUFF BUTTE CANYON CAPE CAVERN CHASM CLIFF COVE
CRATER CREEK DELTA DUNE ESTUARY FJORD FOOTHILL FOREST GEYSER GLACIER GLADE
GORGE GROTTO GULLY HARBOR HEADLAND HIGHLAND HILL INLET ISLAND ISTHMUS
JUNGLE LAGOON LAKE MARSH MEADOW MESA MOOR MORAINE MOUNTAIN OASIS PLATEAU
PRAIRIE RAPIDS RAVINE REEF RIDGE RIVER SAVANNA SHOAL SHORE SPRING STEPPE
STRAIT SUMMIT SWAMP THICKET TUNDRA VALLEY VOLCANO WATERFAL WETLAND
""",
"tools": """
ADZE ANCHOR AUGER AWL AXLE BELLOWS CALIPER CHISEL CLAMP COMPASS CRANK
CROWBAR DRILL FILE FORGE FURNACE GRINDER HAMMER HANDSAW HATCHET HOIST
JACKPLAN LADDER LANTERN LATHE LEVER MALLET MITER PLIERS PULLEY RASP RATCHET
RIVET SANDER SCALPEL SCYTHE SHEARS SHOVEL SICKLE SLEDGE SPADE SPANNER
SPINDLE STAPLER TONGS TREADLE TROWEL VISE WEDGE WINCH WRENCH ANVILS
""",
"instruments": """
BAGPIPE BANJO BASSOON BELL BUGLE CELLO CHIME CLARINET CORNET CYMBAL DRUM
DULCIMER FIDDLE FIFE FLUTE GONG GUITAR HARP HORN KAZOO LUTE LYRE MANDOLIN
MARIMBA OBOE OCARINA ORGAN PIANO PICCOLO RATTLE REBEC RECORDER SACKBUT
SITAR TABOR TAMBOUR TIMPANI TRIANGLE TROMBONE TRUMPET TUBA UKULELE VIOLA
VIOLIN WHISTLE XYLOPHON ZITHER
""",
"celestial": """
APOGEE ASTEROID AURORA COMET CORONA COSMOS CRESCENT DAWN DUSK ECLIPSE
EQUINOX GALAXY HALO HORIZON METEOR MOON NADIR NEBULA NOVA ORBIT PENUMBRA
PERIGEE PLANET PULSAR QUASAR SOLSTICE STARDUST SUNRISE SUNSET SUPERNOV
TWILIGHT UMBRA ZENITH ZODIAC ASTERISM
""",
"vessels": """
BARGE BARQUE BRIGAN CANOE CARAVEL CATAMARA CLIPPER COBLE CORVETTE CUTTER
DHOW DINGHY DORY DREDGER FERRY FRIGATE GALLEON GALLEY GONDOLA JUNK KAYAK
KETCH LAUNCH LIFEBOAT LONGBOAT LUGGER PINNACE PUNT RAFT SAMPAN SCHOONER
SCOW SKIFF SLOOP SMACK TANKER TRAWLER TRIMARAN TUGBOAT UMIAK WHALER YACHT
YAWL
""",
"buildings": """
ABBEY AQUEDUCT ARCADE ARCH BARN BASTION BEACON BELFRY BRIDGE BUNKER
CASTLE CAUSEWAY CHAPEL CISTERN CITADEL COTTAGE CRYPT CUPOLA DOVECOTE
DRAWBRID FOUNDRY GARRISON GATEHOUSE GRANARY HANGAR HARBOUR KEEP KILN
LIGHTHOU MANOR MILLHOUS MINARET MONASTER OBELISK OUTPOST PAGODA PARAPET
PAVILION PIER PORTICO PRIORY PYRAMID RAMPART ROTUNDA SILO SMITHY SPIRE
STABLE TOWER TURRET VIADUCT WATCHTOW WINDMILL
""",
"colours": """
AMARANTH AUBURN AZURE BEIGE BISQUE CARMINE CELADON CERISE CERULEAN CHARCOAL
CHESTNUT COBALTIC CRIMSON CYAN EBONY ECRU FUCHSIA GARNETIC HELIOTRO INDIGO
IVORY LAVENDER LILAC MAGENTA MAROON MAUVE OCHRE OLIVINE PERIWINK PLUM
RUSSET SAFFRON SALMON SCARLET SEPIA SIENNA SORREL TAUPE TEAL UMBER
VERMILIO VIOLET VIRIDIAN
""",
"fish": """
ANCHOVY BARBEL BARRACUD BASS BLENNY BREAM BRILL CARP CATFISH CHUB COALFISH
COD CONGER DACE DOGFISH DORADO EEL FLOUNDER GAR GOBY GRAYLING GROUPER
GUDGEON GUPPY HADDOCK HAKE HALIBUT HERRING KIPPER LAMPREY LING LOACH
MACKEREL MARLIN MINNOW MULLET PERCH PIKE PILCHARD PLAICE POLLOCK POMPANO
RAY ROACH RUDD SAILFISH SALMON SARDINE SAWFISH SCULPIN SHAD SKATE SMELT
SNAPPER SOLE SPRAT STINGRAY SUNFISH TARPON TENCH TETRA TROUT TUNA TURBOT
WHITING WRASSE
""",
"insects": """
ANTLION APHID BEETLE BUMBLE CADDIS CICADA CRICKET DAMSELFL DRONE EARWIG
FIREFLY GADFLY GLOWWORM GNAT GRUB HORNET KATYDID LACEWING LADYBIRD LOCUST
MANTIS MAYFLY MIDGE MOTH SAWFLY SCARAB SILKWORM SKIPPER STONEFLY TERMITE
THRIPS WEEVIL CENTIPED MILLIPED SCORPION SPIDER TARANTUL WOODLOUS
""",
"fruits": """
ALMOND APPLE APRICOT AVOCADO BANANA BARLEY BILBERRY BRAMBLES CASHEW
CHERRIES CHICORY CITRON CLOVE CRANBERR CURRANT DAMSON DATE ENDIVE FENNEL
FIG GINGER GOURD GRAPE GUAVA LEEK LEMON LENTIL LIME LYCHEE MANGO MARROW
MEDLAR MELON MILLET NUTMEG OATS PAPAYA PARSNIP PAWPAW PEACH PEANUT PEAR
PEPPER PIMENTO PLANTAIN POMELO PUMPKIN QUINCE RADISH RAISIN RHUBARB RYE
SESAME SHALLOT SORGHUM SOYBEAN SPELT SQUASH TAMARIND TANGELO TURNIP VANILLA
WALNUTS YAM
""",
"fabrics": """
BROCADE BUCKRAM BURLAP CALICO CAMBRIC CANVAS CASHMERE CHENILLE CHIFFON
CHINTZ CORDUROY COTTON CREPE DAMASK DENIM FLANNEL FLEECE GABARDIN GAUZE
GINGHAM HESSIAN HOMESPUN JERSEY LACEWORK LINEN MOHAIR MUSLIN NANKEEN
ORGANDY PERCALE PLAID POPLIN SACKING SATEEN SATIN SEERSUCK SERGE SILKS
TAFFETA TARTAN TWEED TWILL VELOUR VELVET VOILE WORSTED YARN
""",
}

MODIFIERS = """
ABANDONED ACID AGED AMBER ANCIENT ANGLED ARCTIC ARID ASHEN AUTUMN BARBED
BARE BATTERED BEACHED BENT BITTER BLEACHED BLIND BLUNT BOILING BOLD BONY
BRAIDED BRASSY BRAVE BRIEF BRIGHT BRINY BRISK BROAD BROKEN BRONZED BUOYANT
BURIED BURNING BUSY CALM CANDID CARVED CAUTIOUS CHALKY CHARRED CHEERFUL
CHILLY CHOSEN CIVIL CLEVER CLIPPED CLOAKED CLOUDED COARSE COILED COLD
COPPERY CORAL CRACKED CRAGGY CRESTED CRIMSON CRISP CROOKED CROWDED CRUMBLED
CURLED CURVED DAMP DAPPLED DARING DARK DAWNING DEEP DENSE DEWY DIMMED
DISTANT DIVIDED DOCILE DORMANT DOTTED DOUBLE DRIFTING DRIPPING DROWSY DRY
DUSKY DUSTY EAGER EARLY EARNEST EARTHEN EASTERN EBBING ECHOING EDGED ELDER
EMPTY ENDLESS ETCHED EVEN EXACT FABLED FADED FAINT FALLEN FALLOW FAMED
FEATHERY FERTILE FIERCE FINAL FIRM FLAKY FLAT FLEETING FLINTY FLOATING
FLOWING FLUTED FOAMING FOGGY FOLDED FONDLY FORGED FORKED FORMAL FRAGRANT
FRAYED FREE FRESH FROSTED FROZEN FRUGAL GALLANT GAUNT GENTLE GILDED GLACIAL
GLASSY GLEAMING GLIDING GLOOMY GLOWING GNARLED GOLDEN GRAINY GRAND GRANITIC
GRAVE GRAY GREEN GRIM GROOVED GUARDED GUSTY HALLOWED HALTING HAMMERED
HANGING HARDY HARSH HASTY HAUNTED HAZY HEAVY HIDDEN HIGH HOARY HOLLOW
HONEST HOODED HOOKED HOPEFUL HUMBLE HUMID HUSHED IDLE INKY INLAND INNER
IRON JAGGED JOLLY KEEN KINDLY KNOTTED LACED LANKY LASTING LATE LAZY LEAFY
LEAN LEVEL LIMBER LIMPID LINED LINGERIN LIQUID LIVELY LOFTY LONE LONG
LOOMING LOOSE LOUD LOWLY LOYAL LUCID LUMPY LUNAR LURKING MAROONED MARSHY
MASSIVE MEEK MELLOW MERRY MIGHTY MILD MILKY MINDFUL MINOR MISTY MOBILE
MODEST MOLTEN MOSSY MOTTLED MOULDED MUDDY MUFFLED MURKY MUTED NAKED NARROW
NEAT NESTED NIMBLE NOBLE NORTHERN NUMB OAKEN OBLIQUE OBSCURE OILED OLDEN
OPAQUE OPEN ORNATE OUTER OVAL PACKED PAINTED PALE PARCHED PASSING PATIENT
PATTERED PEARLY PEBBLED PENDING PERCHED PLACID PLAIN PLEATED PLIANT PLUMED
POINTED POLAR POLISHED POROUS PRAIRIE PRESSED PRIMAL PRISTINE PROUD PRUDENT
QUAINT QUEENLY QUICK QUIET RAGGED RAINY RAMPANT RANDOM RAPID RARE RASPING
RAVENOUS READY RECKLESS REDDISH REEDY REGAL RESTED RESTLESS RIBBED RICH
RIDGED RIGID RIPE RIPPLED RISING RIVEN ROAMING ROARING ROBUST ROCKY ROLLING
ROOTED ROSY ROUGH ROUND ROVING ROYAL RUDDY RUGGED RUMBLING RUSTED RUSTIC
SACRED SALTED SANDY SAVAGE SCARLET SCORCHED SCRAPED SEALED SEARING SEASIDE
SECOND SECRET SEDATE SERENE SHADED SHADOWY SHAGGY SHALLOW SHARP SHEER
SHIFTING SHINING SHORT SHREWD SHUTTERE SILENT SILKEN SILVERED SIMPLE SINGLE
SINKING SLANTED SLEEPING SLENDER SLOPING SLOW SMOKY SMOOTH SNOWY SOARING
SODDEN SOFT SOLAR SOLEMN SOLID SOMBRE SOOTHING SOOTY SOUTHERN SPARSE
SPECKLED SPENT SPIKED SPIRAL SPLASHED SPOTTED SPRAWLED SPRINGY SQUARE
STAINED STALWART STARLIT STARRY STEADY STEEP STERN STILL STOIC STONY
STORMY STOUT STRAIGHT STRANDED STRAY STRIPED STRONG STUBBLED STURDY SUDDEN
SULLEN SUNKEN SUNLIT SUNNY SUPPLE SWAYING SWEEPING SWEET SWIFT SWIRLING
TACIT TALL TAMED TANGLED TAPERED TARNISHE TATTERED TAWNY TEEMING TEMPERED
TENDER TENSE TEPID TERSE THAWING THICK THIN THIRSTY THORNY THREADED
THRIVING THUNDERI TIDAL TIDY TIGHT TIMBERED TIMELY TIMID TINNED TIRELESS
TOWERING TRAILING TRANQUIL TRUSTY TUFTED TUMBLING TURNING TWILIT TWINED
TWISTED UNBOWED UNEVEN UNIFORM UNLIT UNTAMED UPLAND UPPER UPRIGHT URBAN
VACANT VAGRANT VALIANT VAPOROUS VARIED VAST VEILED VELVETY VERDANT VEXED
VIGILANT VIVID VOCAL WAKEFUL WANDERIN WANING WARM WARY WASHED WATCHFUL
WATERY WAVERING WAXEN WEARY WEATHERE WESTERN WHIRLING WHISPERI WHITENED
WIDE WILD WILTED WINDING WINDSWEP WINGED WINTRY WIRY WISE WISTFUL WITHERED
WOODEN WOOLLY WORN WOVEN YAWNING YEARNING YELLOWED YIELDING YOUNG ZEALOUS
ZIGZAG
"""


def soundex(word: str) -> str:
    codes = {**dict.fromkeys("BFPV", "1"), **dict.fromkeys("CGJKQSXZ", "2"),
             **dict.fromkeys("DT", "3"), "L": "4",
             **dict.fromkeys("MN", "5"), "R": "6"}
    first, rest = word[0], word[1:]
    out, prev = first, codes.get(first, "")
    for ch in rest:
        code = codes.get(ch, "")
        if code and code != prev:
            out += code
        if ch not in "HW":
            prev = code
    return (out + "000")[:4]


def edit_distance(a: str, b: str) -> int:
    if abs(len(a) - len(b)) > 1:
        return 2
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1]


def clean(raw: str) -> list[str]:
    return [w for w in raw.split() if w]


def filter_list(words, taken_soundex, taken_words, label, all_kept=None):
    # all_kept spans every category, because a codeword's noun can come from
    # any of them — CIVET and RIVET must not both survive just because one is
    # an animal and the other a tool.
    kept, dropped = [], []
    if all_kept is None:
        all_kept = kept
    for w in words:
        if not re.fullmatch(r"[A-Z]{3,8}", w):
            dropped.append((w, "shape"))
            continue
        if w in NATO or w in PROCEDURAL:
            dropped.append((w, "reserved"))
            continue
        if w in TRUNCATED:
            dropped.append((w, "truncated"))
            continue
        if w in taken_words:
            dropped.append((w, "duplicate"))
            continue
        sx = soundex(w)
        if sx in taken_soundex:
            dropped.append((w, f"soundex~{taken_soundex[sx]}"))
            continue
        close = next((k for k in all_kept if edit_distance(w, k) < 2), None)
        if close:
            dropped.append((w, f"editdist~{close}"))
            continue
        kept.append(w)
        if all_kept is not kept:
            all_kept.append(w)
        taken_words.add(w)
        taken_soundex[sx] = w
    return kept, dropped


def main():
    (OUT / "nouns").mkdir(parents=True, exist_ok=True)
    taken_soundex, taken_words = {}, set()
    total = 0
    report = []

    mods, dropped = filter_list(clean(MODIFIERS), taken_soundex, taken_words, "modifiers")
    (OUT / "modifiers.txt").write_text("\n".join(sorted(mods)) + "\n")
    report.append(("modifiers", len(mods), len(dropped)))

    # Nouns get their own namespace: a modifier and a noun never collide in
    # use, so they only need to be distinct within their own list.
    noun_soundex, noun_words, all_nouns = {}, set(), []
    for name, raw in RAW.items():
        words, dropped = filter_list(clean(raw), noun_soundex, noun_words, name, all_nouns)
        (OUT / "nouns" / f"{name}.txt").write_text("\n".join(sorted(words)) + "\n")
        report.append((name, len(words), len(dropped)))
        total += len(words)

    for name, kept, dropped in report:
        print(f"{name:14s} kept={kept:4d} dropped={dropped:3d}")
    print(f"\nmodifiers={len(mods)}  nouns={total}  combinations={len(mods)*total:,}")


if __name__ == "__main__":
    main()
